---
title: "R Notebook"
output: html_notebook
---

```{r}
city<-read.csv("CityData.csv")
library(ggplot2)
head(city)
```
```{r}
cityplot<-ggplot(data=city)+
  geom_point(aes(x=xid,y=yid))+
  geom_text(aes(x=xid,y=yid+10,label=cid))
cityplot
```
```{r}
direction<-read.csv("In_situMeasurementforTraining_201712.csv")
format(object.size(direction),units="Mb")
```
```{r}
length(unique(direction$date_id)) # only five days
length(unique(direction$hour)) # only 18 hours 
unique(direction$hour)
```
```{r}
# subset only one day 
dayone<-which(direction$date_id==1)
length(dayone)/length(direction$date_id) 

```
```{r}
head(direction)
```

```{r}
sample.danger<-direction$wind>=15
```

```{r}
cityplot+
  geom_point(aes(x=xid,y=yid,col="red"),data=direction[sample.danger,])
# almost every part of this land 
```

```{r}
paste(i,i+3)

```

```{r}
plotmy<-function(date.index,hour.index){
  cityplot+
  geom_point(aes(x=xid,y=yid,col="red"),data=direction[sample.danger&direction$date_id==date.index & direction$hour==hour.index,])+
    labs(title=paste("date:",date.index,"hour:",hour.index))
}
plotmy(1,3)
```

```{r}
for(i in 1:5){
  for (j in 3:20){
    print(plotmy(i,j))
  }
}
```






